import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState } from 'react';
import type { PropsWithChildren } from 'react';
import { useRuntimeCatalogProducts } from '../data/runtime-catalog';
import { addCartItem, CART_STORAGE_KEY, clearCart, getProductCartLimit, isProductAvailable, parseStoredCartJson, removeCartItem, serializeCart, setCartItemQuantity, summarizeCart } from './model';
import type { CartItem, StoredCart } from './model';
export type CartContextValue = Readonly<{ add: (productId: string, quantity?: number) => boolean; clear: () => void; items: readonly CartItem[]; itemCount: number; liveMessage: string; remove: (productId: string) => void; setQuantity: (productId: string, quantity: number) => void; storedItems: StoredCart['items']; total: number }>;
const CartContext = createContext<CartContextValue | null>(null);
export function CartProvider({ children }: PropsWithChildren) {
  const products = useRuntimeCatalogProducts(); const initialCart = useMemo(() => readInitialCart(products), []); const [cart, setCart] = useState<StoredCart>(initialCart); const cartRef = useRef(initialCart); const [liveMessage, setLiveMessage] = useState(''); const skipNextPersistence = useRef(false);
  const availableProducts = useMemo(() => new Map(products.filter(isProductAvailable).map((product) => [product.id, product])), [products]);
  useEffect(() => { const normalized = parseStoredCartJson(serializeCart(cartRef.current), products); if (serializeCart(normalized) === serializeCart(cartRef.current)) return; cartRef.current = normalized; setCart(normalized); }, [products]);
  useEffect(() => { if (skipNextPersistence.current) { skipNextPersistence.current = false; return; } try { window.localStorage.setItem(CART_STORAGE_KEY, serializeCart(cart)); } catch { /* memoria */ } }, [cart]);
  useEffect(() => { const handleStorage = (event: StorageEvent) => { if (event.key !== CART_STORAGE_KEY) return; const incoming = parseStoredCartJson(event.newValue, products); if (serializeCart(incoming) === serializeCart(cartRef.current)) return; cartRef.current = incoming; skipNextPersistence.current = true; setCart(incoming); setLiveMessage('El carrito se actualizó desde otra pestaña.'); }; window.addEventListener('storage', handleStorage); return () => window.removeEventListener('storage', handleStorage); }, [products]);
  const summary = useMemo(() => summarizeCart(cart, products), [cart, products]);
  const add = useCallback((productId: string, quantity = 1): boolean => { const product = availableProducts.get(productId); if (product === undefined) { setLiveMessage('No se pudo agregar el producto.'); return false; } const current = cartRef.current; const next = addCartItem(current, productId, quantity, getProductCartLimit(product)); const changed = next !== current; if (changed) { cartRef.current = next; setCart(next); } setLiveMessage(changed ? 'Producto agregado al carrito.' : 'No hay stock suficiente para agregar esa cantidad.'); return changed; }, [availableProducts]);
  const setQuantity = useCallback((productId: string, quantity: number) => { const product = availableProducts.get(productId); if (product === undefined) { setLiveMessage('El producto ya no está disponible.'); return; } const current = cartRef.current; const next = setCartItemQuantity(current, productId, quantity, getProductCartLimit(product)); if (next === current) { setLiveMessage('La cantidad supera el stock disponible o no es válida.'); return; } cartRef.current = next; setCart(next); setLiveMessage('Cantidad actualizada.'); }, [availableProducts]);
  const remove = useCallback((productId: string) => { const current = cartRef.current; const next = removeCartItem(current, productId); if (next === current) return; cartRef.current = next; setCart(next); setLiveMessage('Producto eliminado del carrito.'); }, []);
  const clear = useCallback(() => { const current = cartRef.current; const next = clearCart(current); if (next === current) return; cartRef.current = next; setCart(next); setLiveMessage('Carrito vaciado.'); }, []);
  const value = useMemo<CartContextValue>(() => ({ add, clear, items: summary.items, itemCount: summary.itemCount, liveMessage, remove, setQuantity, storedItems: cart.items, total: summary.total }), [add, cart.items, clear, liveMessage, remove, setQuantity, summary]);
  return <CartContext.Provider value={value}>{children}<div className="visually-hidden" aria-live="polite" aria-atomic="true">{liveMessage}</div></CartContext.Provider>;
}
export function useCart(): CartContextValue { const value = useContext(CartContext); if (value === null) throw new Error('useCart debe usarse dentro de CartProvider.'); return value; }
function readInitialCart(products: ReturnType<typeof useRuntimeCatalogProducts>): StoredCart { if (typeof window === 'undefined') return parseStoredCartJson(null, products); try { return parseStoredCartJson(window.localStorage.getItem(CART_STORAGE_KEY), products); } catch { return parseStoredCartJson(null, products); } }
