import { useEffect, useState } from 'react';
import { trackAnalyticsEvent } from '../analytics/client'; import { useCart } from '../cart/CartContext'; import { isProductAvailable } from '../cart/model'; import { formatAvailability, formatProductPrice } from '../catalog/catalog'; import type { CatalogProductDetail } from '../catalog/model'; import { getAuthorizedProduct } from '../data/authorized-commercial-data'; import { loadRuntimeProductDetail } from '../data/runtime-catalog'; import { AppLink } from '../routing/AppLink'; import { appPaths } from '../routing/routes'; import type { Navigate } from '../routing/routes';
type ProductPageProps=Readonly<{navigate:Navigate;productSlug:string}>;
export function ProductPage({navigate,productSlug}:ProductPageProps){const{add}=useCart();const baseSummary=getAuthorizedProduct(productSlug);const[detail,setDetail]=useState<CatalogProductDetail|null>(null);const[resolved,setResolved]=useState(false);const[loadError,setLoadError]=useState<string|null>(null);
useEffect(()=>{let active=true;setResolved(false);setLoadError(null);setDetail(null);void loadRuntimeProductDetail(productSlug).then((loaded)=>{if(active){setDetail(loaded);setResolved(true);}}).catch((error:unknown)=>{if(active){setLoadError(error instanceof Error?error.message:'No se pudo cargar el producto.');setResolved(true);}});return()=>{active=false;};},[productSlug]);
const summary=detail??(resolved?undefined:baseSummary);useEffect(()=>{if(summary!==undefined)void trackAnalyticsEvent('product_view',{path:summary.path,productId:summary.id});},[summary?.id,summary?.path]);
if(summary===undefined)return <section className="product-page section" aria-labelledby="product-title"><div className="container product-page-shell"><AppLink className="page-back-link" navigate={navigate} to={appPaths.catalog}>Volver al catálogo</AppLink><h1 id="product-title">{resolved?'Producto no encontrado':'Cargando producto…'}</h1>{loadError===null?null:<p role="alert">{loadError}</p>}</div></section>;
const images=detail?.images??(summary.primaryImage===undefined?[]:[summary.primaryImage]);const availability=formatAvailability(summary.availability,summary.stockQuantity);const available=isProductAvailable(summary);
return <section className="product-page section" aria-labelledby="product-title"><div className="container product-page-shell"><AppLink className="page-back-link" navigate={navigate} to={appPaths.catalog}>Volver al catálogo</AppLink><div className="product-page-grid"><div className="product-gallery" aria-label={`Imágenes de ${summary.name}`}>{images.length===0?<div className="product-image-placeholder product-image-placeholder-detail" role="img" aria-label="Imagen no disponible">Imagen no disponible</div>:images.map((image)=><img className="product-detail-image" src={image.src} alt={image.alt} loading="lazy" decoding="async" key={image.src}/>)}</div><div className="product-page-content"><p className="eyebrow">Producto</p><h1 id="product-title">{summary.name}</h1>{summary.categorySlugs.length===0?null:<p className="product-category-links">{summary.categorySlugs.map((slug,index)=><span key={slug}>{index===0?null:', '}<AppLink navigate={navigate} to={`/tienda/categoria/${slug}/`}>{summary.categoryNames[index]}</AppLink></span>)}</p>}{summary.shortDescription===undefined?null:<p className="product-short-description">{summary.shortDescription}</p>}<dl className="product-facts">{summary.presentation===undefined?null:<div><dt>Presentación</dt><dd>{summary.presentation}</dd></div>}<div><dt>Precio</dt><dd>{formatProductPrice(summary.price)}</dd></div>{summary.salePrice===undefined?null:<div><dt>Precio promocional</dt><dd>{formatProductPrice(summary.salePrice)}</dd></div>}{summary.sku===undefined?null:<div><dt>SKU</dt><dd>{summary.sku}</dd></div>}{availability===null?null:<div><dt>Disponibilidad</dt><dd>{availability}</dd></div>}</dl><button className="button button-primary product-page-add" type="button" disabled={!available} onClick={()=>{if(add(summary.id))void trackAnalyticsEvent('cart_add',{path:summary.path,productId:summary.id});}}>{available?'Agregar al carrito':'Producto no disponible'}</button></div></div>{!resolved?<p role="status">Cargando información detallada…</p>:null}{loadError===null?null:<p role="alert">{loadError}</p>}{detail?.description===undefined?null:<section className="product-description" aria-labelledby="product-description-title"><h2 id="product-description-title">Descripción</h2>{detail.description.split('\n').map((p,i)=>p===''?null:<p key={`${summary.slug}-${i}`}>{p}</p>)}</section>}{detail===null||detail.variants.length===0?null:<section className="product-variants" aria-labelledby="product-variants-title"><h2 id="product-variants-title">Presentaciones disponibles</h2><ul>{detail.variants.map((v,i)=><li key={`${summary.slug}-variant-${i}`}>{v.title??`Variante ${i+1}`} — {formatProductPrice(v.price)}</li>)}</ul></section>}</div></section>;
}
